# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme: "blowfish" # UNCOMMENT THIS LINE

baseURL: "https://profile.evaron.ru"
defaultContentLanguage: "ru"
languageCode: "ru"

# pluralizeListTitles: "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT: true
summaryLength: 0

buildDrafts: false
buildFuture: false

enableEmoji: true

languages:
  en:
    contentDir: "content/en"
  ru:
    contentDir: "content/ru"

params:
  images:
    - "site/site-image.jpg"

pagination:
  pagerSize: 100

imaging:
  anchor: "Center"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  series: "series"

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

related:
  threshold: 0
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 100
    - name: "series"
      weight: 50
    - name: "authors"
      weight: 20
    - name: "date"
      weight: 10
    - name: "fragmentrefs"
      type: "fragments"
      weight: 10
      applyFilter: false

markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ["\\[", "\\]"]
            - ["$$", "$$"]
          inline:
            - ["\\(", "\\)"]
