languageCode = "ru"
languageName = "Русский"
languageDirection = "ltr"
weight = 1

title = "Профиль"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Пётр Галонза. Здесь вы найдёте информацию обо мне, моих навыках, проектах и контактные данные."

[params.author]
  name = "Пётр Галонза"
  image = "img/profile-photo.jpg"
  headline = "DevOps-инженер"
  bio = "DevOps-инженер"
  links = [
     { email = "mailto:p.galonza@evaron.ru" },
     { github = "https://github.com/pgalonza" },
     { gitlab = "https://gitlab.com/pgalonza" },
     { dzen = "https://dzen.ru/pgalonza" },
     { notes = "https://notes.evaron.ru/" },
     { setka = "https://set.ki/NFb3KGJ" },
     { hh_mono = "site/resume.pdf" },
  ]
