languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Profile"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  displayName = "EN"
  isoCode = "en"

  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Peter Galonza. Here you will find information about me, my skills, projects and contact details."

[params.author]
  name = "Peter Galonza"
  image = "img/profile-photo.jpg"
  headline = "DevOps-engineer"
  bio = "DevOps-engineer"
  links = [
     { email = "mailto:p.galonza@evaron.ru" },
     { github = "https://github.com/pgalonza" },
     { gitlab = "https://gitlab.com/pgalonza" },
     { dzen = "https://dzen.ru/pgalonza" },
     { notes = "https://notes.evaron.ru/" },
     { setka = "https://set.ki/NFb3KGJ" },
     { hh_mono = "https://naryan-mar.hh.ru/resume/acd1d42eff0279daab0039ed1f375076567a69" },
     { habr_career = "https://career.habr.com/pgalonza" },
  ]
